name: Build and Deploy

on:
  push:
    branches:
      - main # Trigger workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure all branches are available

      # Step 2: Remove unnecessary files
      - name: Remove unnecessary files
        shell: bash
        run: |
          shopt -s extglob
          rm -rf !(dist|classes|plugin.php)

      # Step 3: Remove the .github folder
      - name: Remove .github folder
        run: rm -rf .github

      # Step 4: Configure Git
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      # Step 5: Check if staging branch exists and create it from main if it doesn't
      - name: Check if staging branch exists
        run: |
          git fetch origin staging:staging || git checkout -b staging
          git checkout staging
          git merge main --no-edit || echo "No changes to merge"
          git push origin staging

      # Step 6: Check if production branch exists and create from staging if it doesn't
      - name: Check if production branch exists
        run: |
          git fetch origin production:production || git checkout -b production staging
          git push origin production

      # Step 7: Commit and push changes to staging / Create a PR to production
      - name: Commit and push changes to staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git commit -m "Deploy plugin with only dist, classes, and plugin.php" || echo "No changes to commit"
          git remote set-url origin https://tarycare:${{ secrets.GITHUB_TOKEN }}@github.com/tarycare/wp-react.git
          git push origin HEAD:staging --force

      # Step 8: Create a Pull Request from staging to production
      - name: Create Pull Request to Production
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: production
          source_branch: staging
          pr_title: "Deploy from Staging to Production"
          pr_body: "This is an automated PR to merge staging into production after build and deploy."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
